spring.application.name=card-service
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5436/neobank_cards
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8090/realms/neobank

spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.probes.enabled=true
account-service.url=http://localhost:8082
neobank.internal-api-key=neobank-internal-dev-key
